version: "3"
services:
  app:
    build: .
    container_name: iot-api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    container_name: iot-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminDev
      MONGO_INITDB_DATABASE: db_dev
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
