version: "3"
services:
  app:
    build: .
    container_name: iot-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: mongo
    container_name: iot-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
